#!/bin/bash
SBT=./sbt

set -o nounset

abort_check() {
  if [ $1 != 0 ] ; then
    echo "Aborted"
    exit $1
  fi
}

# build, test, package
$SBT clean ; abort_check $?
$SBT test ; abort_check $?
$SBT package ; abort_check $?

# tag
tag="0.0.0-1"
latestgittag=$(git describe --abbrev=0 --tags)
echo "Most recent tag in this branch is $latestgittag"
unset userin
read -p "Tag [$tag]: " userin
if [ "$userin" ]; then
  tag=$userin
fi
tag_message="Next"
unset userin
read -p "Tag message [$tag_message]: " userin
if [ "$userin" ]; then
  tag_message=$userin
fi
git tag -a -m "$tag_message" $tag ; abort_check $?

# deploy
war_name="docreg+web-"
server_host="webapp-vm01"
unset userin
read -p "Deploy to [$server_host]: " userin
if [ "$userin" ]; then
  server_host=$userin
fi
war=$(find target -iname '*.war')
remote_war="$war_name$tag.war"
echo "Backup copy to ./backup/$remote_war"
cp $war ./backup/$remote_war
echo "Deploying $war as $remote_war to $server_host"
scp $war $server_host:$remote_war ; abort_check $?
#ssh $server_host cp $remote_war /var/lib/jetty/webapps/docreg.war
#ssh $server_host touch /etc/jetty/contexts/docreg.xml
