#!/bin/bash
SBT=./sbt
server_host="webapp-vm01"
war_name="docreg+web-"
set -o nounset

abort_check() {
  if [ $1 != 0 ] ; then
    echo "Aborted"
    exit $1
  fi
}

# build, test, package
$SBT clean ; abort_check $?
$SBT test ; abort_check $?
$SBT package ; abort_check $?

# tag
tag="0.0.0-1"
unset userin
read -p "Tag [$tag]: " userin
if [ "$userin" ]; then
  tag=$userin
fi
tag_message="Next"
unset userin
read -p "Tag message [$tag_message]: " userin
if [ "$userin" ]; then
  tag_message=$userin
fi
git tag -a -m "$tag_message" $tag ; abort_check $?

# deploy
war=$(find target -iname '*.war')
remote_war="$war_name$tag.war"
scp $war $server_host:$war_name$tag.war ; abort_check $?
#ssh $server_host cp $remote_war /var/lib/jetty/webapps/docreg.war
#ssh $server_host touch /etc/jetty/contexts/docreg.xml
